version: "3.9"
services:

  # build a current Ubuntu container
  ubuntu1:
    image: ubuntu
    command: bash -c "apt-get update && apt-get -y install iputils-ping iproute2 net-tools mtr-tiny nano tcpdump nmap traceroute && /bin/bash"
    container_name: ubuntu1
    tty: true
    cap_add:
        - ALL
    privileged: true
    networks:
      net-10:

  # build another current Ubuntu container
  ubuntu2:
    image: ubuntu
    command: bash -c "apt-get update && apt-get -y install iputils-ping iproute2 net-tools mtr-tiny nano tcpdump nmap traceroute && /bin/bash"
    container_name: ubuntu2
    tty: true
    cap_add:
        - ALL
    privileged: true
    networks:
      net-10:

networks:
  net-10:
    ipam:
      config:
        - subnet: 10.9.0.0/24
